### ISSUE TITLE
🐛 Search function breaks easily

### ISSUE THREAD

**Issue by Pleasant-exe** [hoangvu12/megumin#10]
**Describe the bug**
The search function seems to be broken and when it works the audio is not working, however when i manually add a url it works fine. 

**How To Reproduce**
1. /play (song name)

**Expected behavior**
There was an error executing that command. is outputted in discord

**Environment (add if possible)**
* 18.20.2

**Additional information & screenshots**
```
3|evobot2  | Bot ready!

3|evobot2  | SyntaxError: Unexpected token < in JSON at position 0
3|evobot2  |     at JSON.parse (<anonymous>)
3|evobot2  |     at parseJSONFromBytes (node:internal/deps/undici/undici:5584:19)
3|evobot2  |     at successSteps (node:internal/deps/undici/undici:5555:27)
3|evobot2  |     at fullyReadBody (node:internal/deps/undici/undici:1665:9)
3|evobot2  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
3|evobot2  |     at async specConsumeBody (node:internal/deps/undici/undici:5564:7)
3|evobot2  |     at async search (/home/discord/personal/megumin/utils/invidious.ts:186:17)
3|evobot2  |     at async searchVideo (/home/discord/personal/megumin/utils/invidious.ts:194:16)
3|evobot2  |     at async Function.from (/home/discord/personal/megumin/structs/Song.ts:40:22)
3|evobot2  |     at async Object.execute (/home/discord/personal/megumin/commands/play.ts:56:14)
```

**Comment by hoangvu12** [comment]
The default invidious instance is [inv.nadeko.net](https://inv.nadeko.net/feed/popular) but sometimes it shows a captcha (probably using CloudFlare), which I believe is causing the error
